version: '3.8'

services:
  tiktok-app:
    image: sonabhandari20/tiktok
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./target:/app
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: always
